### ISSUE TITLE
The terminal just shows this:

### ISSUE THREAD

**Issue by hjtfir** [CaBz/the-button#3]
![screen shot 2015-04-24 at 5 13 28 pm](https://cloud.githubusercontent.com/assets/12105244/7328686/74957960-eaa5-11e4-8711-9e4f9951bc3f.png)

**Comment by CaBz** [comment]
Hey,

The console is expecting you to have redis installed in local. If you don't want to have redis and use it, update the main.js file to set the options to false like this:

    var options = {
	  save_data: false,
	  load_data: false
    };

**Comment by CaBz** [comment]
Hey dude,

I've kind of upgraded the readme file. Have a look again and see if you can manage to fix your issue?

**Comment by hjtfir** [comment]
It works! Thank you so much. 
![screen shot 2015-04-25 at 12 35 38 pm](https://cloud.githubusercontent.com/assets/12105244/7333722/aaadea9e-eb47-11e4-8e26-30fe1f1264d3.png)
